### ISSUE TITLE
Issues using tigrisfs inside a Fly Machine

### ISSUE THREAD

**Issue by infovore** [tigrisdata/tigrisfs#14]
It's currently not possible to correctly use the packaged version as documented inside a Fly Machine.

`dpkg -i` attempts to set up a `systemctl` process; this is, of course, not available inside a container.

However, the install _does_ successfully install `tigrisfs` to `/usr/bin`.

Attempting to run this binary leads to this error: `Failed to connect to syslog error="Unix syslog delivery error"`

which again, feels related to the above?

I _have_ successfully run GeeseFS on a Fly Machine to connect to Tigris. The fact that Tigris' own fork of GeeseFS won't run inside a Fly machine - especially given the Fly/Tigris relationship - feels like an oversight, but a frustrating one....

**Comment by infovore** [comment]
OK, I have it working in a Fly Machine. I don't think it's quite working correctly.

First, I download the `deb` and install it.

```
Selecting previously unselected package tigrisfs.
(Reading database ... 23294 files and directories currently installed.)
Preparing to unpack tigrisfs_1.1.2_linux_amd64.deb ...
Unpacking tigrisfs (1.1.2) ...
Setting up tigrisfs (1.1.2) ...
/var/lib/dpkg/info/tigrisfs.postinst: 5: systemctl: not found
dpkg: error processing package tigrisfs (--install):
 installed tigrisfs package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 tigrisfs
```

The postinstall script fails, but tigris itself installs to `/usr/bin`.

Then, I can call it like so:

```bash
tigrisfs --endpoint https://fly.storage.tigris.dev --log-file stderr BUCKET_NAME /mnt/MNT_POINT
```

I _have_ to specify a non sysctl logfile, and I have to also specify my endpoint (it doesn't default to this tigris endpoint). Once I do that, Tigris mounts correctly.

So my question is: is this expected behaviour/dx inside a Fly Machine?

**Comment by infovore** [comment]
(Finally: just resorted to downloading the binary rather than the `deb`, and all is well.)

**Comment by efirs** [comment]
Thanks for trying out TigrisFS — your feedback is greatly appreciated!

We've addressed the issues you reported:
  * Fixed package installation on systems without systemd ##15 
  * Corrected the default endpoint in package builds #16 
  * Resolved startup failures on systems without syslog #17
Release with the fixes here: https://github.com/tigrisdata/tigrisfs/releases/tag/v1.2.0
 
Let us know if you run into any other issue.

**Comment by infovore** [comment]
@efirs not quite thereL

- package installation works correctly
- default endpoint works correctly
- ignoring syslog still not quite working: when I run `tigrisfs bucket mountpoint`, I get `Apr 17 12:32:35.000000 WRN log/logger.go:62 failed to open syslog. redirecting logs to /var/log/tigrisfs.log error="Unix syslog delivery error"`

Also, you probably want to upgrade the hard links to 1.1.2 in `README.md` - I know to go to the releases page, but clicking the `deb` and `rpm` links in it will take you to 1.1.2.

**Comment by efirs** [comment]
When the process mounts the directory and forks into the background, it logs to syslog by default to avoid cluttering the terminal output.
The message you're seeing is just a warning, informing the user that logs are being redirected to file instead of syslog.

If you prefer to see logs in the terminal, you have two options:

  * Run with --log-file=stderr to explicitly direct logs to standard error.
  * Or run in the foreground using the -f flag — in this mode, logs go to stderr by default.
